/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as WorkDawsonMotorsRouteImport } from './routes/work.dawson-motors'
import { Route as WorkFlightBookingRouteImport } from './routes/work.flight-booking'
import { Route as WorkReflinkAppRouteImport } from './routes/work.reflink-app'
import { Route as WorkReflinkPrototypeRouteImport } from './routes/work.reflink-prototype'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDawsonMotorsRoute = WorkDawsonMotorsRouteImport.update({
  id: '/work/dawson-motors',
  path: '/work/dawson-motors',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFlightBookingRoute = WorkFlightBookingRouteImport.update({
  id: '/work/flight-booking',
  path: '/work/flight-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkReflinkAppRoute = WorkReflinkAppRouteImport.update({
  id: '/work/reflink-app',
  path: '/work/reflink-app',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkReflinkPrototypeRoute = WorkReflinkPrototypeRouteImport.update({
  id: '/work/reflink-prototype',
  path: '/work/reflink-prototype',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/dawson-motors': typeof WorkDawsonMotorsRoute
  '/work/flight-booking': typeof WorkFlightBookingRoute
  '/work/reflink-app': typeof WorkReflinkAppRoute
  '/work/reflink-prototype': typeof WorkReflinkPrototypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/dawson-motors': typeof WorkDawsonMotorsRoute
  '/work/flight-booking': typeof WorkFlightBookingRoute
  '/work/reflink-app': typeof WorkReflinkAppRoute
  '/work/reflink-prototype': typeof WorkReflinkPrototypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/dawson-motors': typeof WorkDawsonMotorsRoute
  '/work/flight-booking': typeof WorkFlightBookingRoute
  '/work/reflink-app': typeof WorkReflinkAppRoute
  '/work/reflink-prototype': typeof WorkReflinkPrototypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/work/dawson-motors'
    | '/work/flight-booking'
    | '/work/reflink-app'
    | '/work/reflink-prototype'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/work/dawson-motors'
    | '/work/flight-booking'
    | '/work/reflink-app'
    | '/work/reflink-prototype'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/work/dawson-motors'
    | '/work/flight-booking'
    | '/work/reflink-app'
    | '/work/reflink-prototype'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WorkDawsonMotorsRoute: typeof WorkDawsonMotorsRoute
  WorkFlightBookingRoute: typeof WorkFlightBookingRoute
  WorkReflinkAppRoute: typeof WorkReflinkAppRoute
  WorkReflinkPrototypeRoute: typeof WorkReflinkPrototypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/dawson-motors': {
      id: '/work/dawson-motors'
      path: '/work/dawson-motors'
      fullPath: '/work/dawson-motors'
      preLoaderRoute: typeof WorkDawsonMotorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/flight-booking': {
      id: '/work/flight-booking'
      path: '/work/flight-booking'
      fullPath: '/work/flight-booking'
      preLoaderRoute: typeof WorkFlightBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/reflink-app': {
      id: '/work/reflink-app'
      path: '/work/reflink-app'
      fullPath: '/work/reflink-app'
      preLoaderRoute: typeof WorkReflinkAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/reflink-prototype': {
      id: '/work/reflink-prototype'
      path: '/work/reflink-prototype'
      fullPath: '/work/reflink-prototype'
      preLoaderRoute: typeof WorkReflinkPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WorkDawsonMotorsRoute: WorkDawsonMotorsRoute,
  WorkFlightBookingRoute: WorkFlightBookingRoute,
  WorkReflinkAppRoute: WorkReflinkAppRoute,
  WorkReflinkPrototypeRoute: WorkReflinkPrototypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
